# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  schedule:
    - cron: "0 */12 * * *"
    
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '22'
    - run: ls
    - run: rm README.md
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name "franciscogsilva"
        git config user.email "javiergonzalezsilva@gmail.com"
        git add README.md
        git commit -m "Update README from Github Actions with latest info" || echo "Nothing to commit"
        git push || echo "Nothing to push"
